language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: chrisparsons83/FFDiscordBot
  bucket: redditffdiscordbot
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: redditffdiscordbot
  key: latest.zip
  bundle_type: zip
  application: RedditFFDiscordBot
  deployment_group: RedditFFDiscordBot
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
