version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - postgres
    # environment:
    #   DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: ffdiscordbot
      POSTGRES_DB: ffdiscordbot