version: '2'

services:
  discord:
    build: .
    command: npm start
    restart: unless-stopped
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - postgres
    # environment:
    #   DATABASE_URL: postgres://ffdiscordbot@postgres/ffdiscordbot
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: ffdiscordbot
      POSTGRES_DB: ffdiscordbot
      POSTGRES_PASSWORD: ffdiscordsomething
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data: